### ISSUE TITLE
Crash after clicking edit

### ISSUE THREAD

**Issue by Hiradpi** [Zgoly/Meteorist#40]
### there is a new bug in the new version that crashes the client when i click on the Edit button   
but the clicking work fine tho

**Crash console log**
```[17:47:53] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: mouseReleased event handler
	at net.minecraft.class_437.method_25412(class_437.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:180) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:202) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:220) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:287) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1349) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.length()" because "this.text" is null
	at meteordevelopment.meteorclient.gui.widgets.input.WTextBox.calculateTextWidths(WTextBox.java:581) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.widgets.input.WTextBox.onCalculateSize(WTextBox.java:81) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.widgets.WWidget.calculateSize(WWidget.java:45) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.calculateSize(WContainer.java:66) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.calculateSize(WContainer.java:66) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.calculateSize(WContainer.java:66) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.DefaultSettingsWidgetFactory.create(DefaultSettingsWidgetFactory.java:88) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.GuiTheme.settings(GuiTheme.java:204) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.GuiTheme.settings(GuiTheme.java:207) ~[meteor-client-0.5.6%20(3).jar:?]
	at zgoly.meteorist.gui.screens.SlotSelectionScreen.initWidgets(SlotSelectionScreen.java:22) ~[meteorist-1.9.jar:?]
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25426(WidgetScreen.java:101) ~[meteor-client-0.5.6%20(3).jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:298) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:1187) ~[client-intermediary.jar:?]
	at zgoly.meteorist.modules.slotclick.SlotClick.lambda$fillWidget$6(SlotClick.java:165) ~[meteorist-1.9.jar:?]
	at meteordevelopment.meteorclient.gui.widgets.pressable.WPressable.onMouseReleased(WPressable.java:28) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.widgets.WWidget.mouseReleased(WWidget.java:96) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.widgets.containers.WContainer.mouseReleased(WContainer.java:142) ~[meteor-client-0.5.6%20(3).jar:?]
	at meteordevelopment.meteorclient.gui.WidgetScreen.method_25406(WidgetScreen.java:136) ~[meteor-client-0.5.6%20(3).jar:?]
	at net.minecraft.class_312.method_1605(class_312.java:101) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	... 22 more```
	
Im worried that it's becuase im using 1.20.4 
if it is please consider fixing the clicking problem on the last version <3 

### Steps to reproduce

I just clicked on the edit button

### Meteorist Version

1.9

### Meteor Version

0.5.6 

### Minecraft Version

1.20.4

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest Meteorist build).

**Comment by Zgoly** [comment]
I think you're right about `1.20.4`. Try using the latest version `1.21` + the latest version of Meteorist [`1.10`](https://github.com/Zgoly/Meteorist/releases/tag/v1.10). If problem persists, please create a new issue
